# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import users.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApplicationer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=10)),
                ('permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApiList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appId', models.CharField(default='', max_length=25)),
                ('appKey', models.CharField(default='', max_length=100)),
                ('publicKey', models.CharField(default='', max_length=180)),
                ('privateKey', models.CharField(default='', max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
            },
        ),
        migrations.CreateModel(
            name='FollowsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '用户关注关联信息',
                'verbose_name_plural': '用户关注关联信息',
            },
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicKey', models.CharField(max_length=250)),
                ('privateKey', models.CharField(max_length=900)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='LikesLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '点赞关联信息',
                'verbose_name_plural': '点赞关联信息',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(storage=users.storage.ImageStorage(), upload_to='photos/', verbose_name='图片')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '相册图片信息',
                'verbose_name_plural': '相册图片信息',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(default='', max_length=150, verbose_name='动态描述')),
                ('Pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('likes_num', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('photo_0', models.ImageField(default='', storage=users.storage.ImageStorage(), upload_to='photos/', verbose_name='图片')),
                ('com_num', models.PositiveIntegerField(default=0, verbose_name='评论数')),
            ],
            options={
                'verbose_name': '动态信息',
                'verbose_name_plural': '动态信息',
            },
        ),
        migrations.CreateModel(
            name='PostsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '收藏关联信息',
                'verbose_name_plural': '收藏关联信息',
            },
        ),
        migrations.CreateModel(
            name='UsersActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, '注册'), (2, '忘记')], default=2, verbose_name='状态')),
                ('code', models.CharField(default='保存后自动生成验证码', max_length=10, verbose_name='验证码')),
                ('hashkey', models.CharField(default='', max_length=100, verbose_name='哈希值')),
            ],
            options={
                'verbose_name': '验证码信息',
                'verbose_name_plural': '验证码信息',
            },
        ),
    ]
