# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-27 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ins_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersactive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='postslink',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins_api.Posts', verbose_name='动态'),
        ),
        migrations.AddField(
            model_name='postslink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='photos',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins_api.Posts', verbose_name='动态'),
        ),
        migrations.AddField(
            model_name='likeslink',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins_api.Posts', verbose_name='动态'),
        ),
        migrations.AddField(
            model_name='likeslink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='followslink',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='关注者'),
        ),
        migrations.AddField(
            model_name='followslink',
            name='To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='被关注者'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ins_api.Posts', verbose_name='动态'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
